# docker-compose.yml for mongo
version: '3.1'

services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATABASE=nest-pokemon
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo:/data/db